AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: ./ 
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: / 
            Method: GET
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
            Action: sts:AssumeRole
            - codestar:SyncResources
            - lambda:CreateFunction
            - lambda:DeleteFunction
            - lambda:AddPermission
            - lambda:UpdateFunction
            - lambda:UpdateFunctionCode
            - lambda:GetFunction
            - lambda:GetFunctionConfiguration
            - lambda:UpdateFunctionConfiguration
            - lambda:RemovePermission
            - lambda:listTags
            - lambda:TagResource
            - lambda:UntagResource
            - iam:PassRole
            Resource:
            - Fn::GetAtt:
              - LambdaTrustRole
              - Arn
 
